[workspace]
name = "longred-forge"
version = "0.1.0"
description = "Longred personal conda package repository"
authors = ["Longred <longredzhong@outlook.com>"]
channels = ["conda-forge", "https://repo.prefix.dev/brads-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tasks]
clean = "deno task clean"
build = "deno task build"
build-test = "deno task build --no-upload"
delete = "deno task delete"
py-update = "python scripts/update.py --dry-run"
py-update-apply = "python scripts/update.py --apply"
py-build = "python scripts/build.py"

[dependencies]
deno = ">=2.6.1,<4.0"
rattler-build = ">=0.54.0,<0.55"
python = ">=3.14.2,<3.15"

[pypi-dependencies]
httpx = ">=0.28.1, <0.29"
PyYAML = ">=6.0, <7.0"
PyGithub = "*"
