[workspace]
name = "longred-forge"
version = "0.1.0"
description = "Longred personal conda package repository"
authors = ["Longred <longredzhong@outlook.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
rattler-build = ">=0.54.0,<0.55"
python = ">=3.14.2,<3.15"

[pypi-dependencies]
httpx = ">=0.28.1, <0.29"
PyYAML = ">=6.0, <7.0"
PyGithub = "*"
